# Generated by Django 5.0 on 2024-01-11 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='details',
            field=models.CharField(default='Checker value', max_length=100),
        ),
        migrations.AddField(
            model_name='features',
            name='name',
            field=models.CharField(default='Attribute name', max_length=100),
        ),
    ]
